### ISSUE TITLE
[Request] Multi-Language Quest Book Content

### ISSUE THREAD

**Issue by claybiockiller** [lorddusk/HQM#165]
I'm Clayblock, a mod localizer from China. 
In my opnion, we can add support for multi-language quest book content(i.e. different content displayed at different language setting). I think it will help us in localization of modpacks.
Clayblock

**Comment by 3TUSK** [comment]
Can't you export the quest as json file, then do the translation stuff and then import back...?

**Comment by airbreather** [comment]
> Can't you export the quest as json file, then do the translation stuff and then import back...?

Not equivalently to the usual stuff, which allows a user to change their language on-the-fly.  However, maybe checking for a string translation for `quests.187.tasks.2.description`, using it if it's found and defaulting if it's not, would be theoretically possible... finding out the quest IDs would not be fun, but my little [tool](https://github.com/airbreather/HQMEditor.git) might help...

We use the [latest version](https://github.com/airbreather/HQMEditor/commit/d752dd4ab8614f3ef3d49d22ba485524625f155e) (realized today that I never pushed the source for this fun stuff) in the [modpack](https://github.com/airbreather/cacophony-inc) we work on that lets us do editing in a [text file](https://github.com/airbreather/cacophony-inc/blob/2d27515c407ad3c7bfc8df7d86a4ec7cef85e39f/data/minecraft/config/hqm/quests.xaml) and then regenerate the .hqm file [on-the-fly during the build process](https://github.com/airbreather/cacophony-inc/blob/2d27515c407ad3c7bfc8df7d86a4ec7cef85e39f/build.bat#L5) while ensuring that old IDs are preserved so that we don't break people's worlds unlike what I assume the JSON editor has a chance of doing because of the way it works.

**Comment by noobanidus** [comment]
This needs a reformatting of the quest information to include keys or alternately some separation of actual value of the description and the visual, which currently can't happen.

**Comment by kirderf1** [comment]
(taken from one of my comments in #539)
For whoever picks up this feature request (maybe it'll be me?), here's a pitfall to avoid:
Assuming that that plan is for to support both raw text (as it is right now) and translation keys, know that raw text shouldn't go through the translation procedure at all (as the translation procedure will most likely have formatting with special characters such as %).

As such, for raw text, it isn't enough to depend on the translation giving back the same string if it did not match a language entry. A distinction need to be made between raw text and translation keys, such that translation (and its formatting) will only be performed on inputted translation keys.
