### ISSUE TITLE
Crash after modpack update

### ISSUE THREAD

**Issue by JasonMcRay** [lorddusk/HQM#177]
I updated my modpack (InfiTech 2) and one of the players reported that their server is crashing after an update. HQM version did not changed. Before and after an update still using 4.4.4.

http://pastebin.com/ppcKNBzq

Multiple other players/server owners did not reported issue like this.

Deleting the HQM save file from the world might solve the issue, but it's not viable solution because everyone would loose their quest progress.

**Comment by Dream-Master** [comment]
I have this situation twice on my server. Every time the Questfile was changed.

**Comment by lorddusk** [comment]
@JasonMcRay & @Dream-Master could you try this version for me? And report if it fixes the issue?
https://www.dropbox.com/s/mucyuw8kqevzk7h/HQM-The%20Journey-4.4.4a.jar?dl=0

**Comment by Cazadorsniper** [comment]
I would test that but can't due to it not being on curse

**Comment by lorddusk** [comment]
you can manually overwrite mods in packs.

**Comment by Dream-Master** [comment]
Will try it later when i be back home.

**Comment by JasonMcRay** [comment]
I was not really able to recreate it. Happened so far only once on one server using my modpack. And I dont think he will still have the hqm save file from the world, because he already deleted it.

**Comment by Dream-Master** [comment]
I try to crash my Testserver with different files but it wont work now. I using Version 4.4.4
Will change my files some more times and let you know if crash with 4.4.4 and solved with 4.4.4a

**Comment by Dream-Master** [comment]
I try more files no crash. Maybe KCauldron is here the Problem. On my testserver i have Thermos installed. Will try restarting more times to be sure.

**Comment by Dream-Master** [comment]
@lorddusk 
Ok i get thise crash now with Version 4.4.4a.

https://gist.github.com/Dream-Master/c00a82c43970392473c11c345900fd14#file-crash

**Comment by lorddusk** [comment]
An unsupported base software is installed: 'thermos, cauldron, craftbukkit, mcpc, kcauldron'. This is NOT supported.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

**Comment by Dream-Master** [comment]
@lorddusk 
I can't, try it because i have two servers where i can test stuff. One have KCauldron one have Thermos. Maybe i can try it with a server on my Desktop Pc and try to yoin via localhost to test it.

**Comment by CaiganMythFang** [comment]
This is a pretty familiar issue with my modpack every time I put out a major update.

It usually happens when quests are changed, specifically when quest chains are added or removed from existing quest lines.

I tried the 4.4.4a linked above, and got the same crash, testing with these conditions
1. Start a new world in a previous version of the modpack (0.1.2)
2. /hqm edit caigan to spawn the quest edit book
3. Progress in quests over multiple pages, making sure quests that change in the next version are 'completed'
4. Close Minecraft, and copy the HardcoreQuestingData folder to the current version of the modpack (0.1.3), in an established world. The new version has changed some quests, breaking some quest chains and moving quests around.
5. Load up the current version and load the established world with the copied over quest data. This will result in a crash. 

This does not seem to happen if a player has not completed a quest in a chain that is later 'broken', via changing or deleting quests.

EDIT : For reference, modpack is The Ferret Business. Forge version 1566.

**Comment by Cazadorsniper** [comment]
I get this crash now with version 4.4.4: http://pastebin.com/LiWyDB4s
,but I did try out the 4.4.4a (posted above) version and that didn't make me crash instantly

**Comment by Dream-Master** [comment]
@JasonMcRay 

What you are doing about this problem?. Not Updating any more or run the server on Forge :).

**Comment by JasonMcRay** [comment]
Our server runs on pure forge. I was not really still able to recreate the crash with 4.4.4. As I mentioned it happend so far only once (at least I got only one report about this). We recently moved one quest to completely different set, with different prereqs and no issue. I would like to say, that its very rare issue, but seeing @CaiganMythFang also having the same issue.... I don't realy know.

Also honestly I did not tested that much, because we are currently quite busy with other stuff.

**Comment by Dream-Master** [comment]
@JasonMcRay 
I have this issue again if i update 4.4.4 to the 4.4.4a version due an Modupdate. 
I find something more out maybe. I  try to export all Quests via Json file and 3 Quest lines on 3 Pages not save any file or a empty file. I guess there is some Quest code which isn't allowed or some sings not be supported but I don't know. Are you able to export all your Quests? My Main Server runs on KCauldron and my Test Server on Thermos. I know this are not supported but I can't run the Server on Forge because i need world guard to protect the Players. Now testing Thermos if this happened there too after an update.

@lorddusk 
@way2muchnoise 

On which side I have to ask for a Kcauldron, Thermos etc. compatible patch ?
I want to keep HQM in the Pack.

**Comment by JasonMcRay** [comment]
In 4.4.4 for some reason the exporting/importing is little bit buggered. I am able to export quests just fine. But when I load them back (either to completely fresh hqm, or to replace the current) all the quest chains gets broken, unconected. Well only the 1st set is fine. Rest becomes unconnected. I asked one of my team to try import again, in case it was only issue on my side.

(BTW as replacement for world guard we are using MyTown on Forge - Not as powerful but suits our needs)

**Comment by Dream-Master** [comment]
@JasonMcRay 
Yes we test it to on the Thermos Server. But for some reason the Server runs much faster with some Bukkit, Thermos, KCauldron then with only Forge. I will run more tests with Thermos tomorrow.

You said 4.4.4 have a problem with import/(export) did 4.4.3 have this too or a nother version?

**Comment by JasonMcRay** [comment]
I havent tested earlier versions. We pretty much just recently added HQM to the pack. So I don't know if it was an issue in earlier versions. When we first tested the import/export on 4.4.4 it was working just fine. But now it is happening. I will open propper issue for the import/export bug if we will confirm it.

**Comment by lorddusk** [comment]
Export > Import is known that it breaks quest lines, that's because if you
import quest 7 before 6 and they are connected. it breaks. Which is common
sense. How can you connect a child to a parent if the parent doesnt exist
yet.

**Comment by JasonMcRay** [comment]
well what was happening is that if I imported, the first set was fine, without any broken lines. But all others were. It kinda breaks the usage of the import. Also my very first import was totally fine without any issues.

I understand that it might disconnect lines connected to different sets. But it breaks ALL of the lines.

**Comment by JasonMcRay** [comment]
Maybe make the import perform 2 steps. 1st - import quests and then it will start connecting. Not sure if it would be possible to make this with json files though.

**Comment by lorddusk** [comment]
Maybe is a big word.
But read this please :

https://www.reddit.com/r/feedthebeast/comments/4fgyfb/im_leaving_the_modding_scene/

**Comment by Dream-Master** [comment]
@lorddusk 
Ok but why some Quests cant be exported and give an empty file or no file?
HQM file:
https://www.dropbox.com/s/3tkbz3whpbe61us/quests.hqm?dl=0

**Comment by JasonMcRay** [comment]
Oh I havent noticed that you are leaving... Sad to see you go, but I definitely understand your decision.

**Comment by JasonMcRay** [comment]
@Dream-Master Just remembered. Export fails if you have quest lines named with "special" characters. Like "/" will cause the file to not be created. Or pretty much anything that you can't put into file name

**Comment by way2muchnoise** [comment]
Closed due to no longer supporting 1.7.10, please check if this problem persists in the latest 1.9.4 version. Saving has had a major rework hopefully this resolves the issues for 1.9+
