### ISSUE TITLE
[1.10.2] Party function not working.

### ISSUE THREAD

**Issue by mobehun** [lorddusk/HQM#228]
HQM Version: HQM-New Heights-5.0.0beta3
Forge Version: forge-12.18.1.2061
Detailed description of the bug and pictures if applicable:
As I've been told this is the issue one of my modpack user has:

> 'The HQM works only for the Hosts client. For the other one the questbook is completly empty, even when trying to make a party, it just says there is no other player on the server.'

**Comment by InjuredWolf** [comment]
Is this with a LAN world or dedicated server?

**Comment by mobehun** [comment]
Dedicated as far as I know.

**Comment by way2muchnoise** [comment]
Could you try [HQM-New Heights-1.10.2-5.1.0alpha2](https://minecraft.curseforge.com/projects/hardcore-questing-mode/files/2396680), which got released this morning and should fix quite some issues.

I'm fairly sure it will fix your issue so I'll close this issue. Feel free to reopen if it still doesn't work.

**Comment by HermoidIronoak** [comment]
I'm having the same issue in a LAN setting with my wife. We are trying to play the Invasion pack by darkosto. If I start a world and she joins me, she doesn't have quests. Vice versa for when she starts a world. The modpack has "HQM-New Heights-1.10.2-5.1.0 alpha4" Thank you for any assistance you can give us

**Comment by way2muchnoise** [comment]
LAN is kinda broken atm, due to me not having to much free time right now there is no fix coming soon. You might wanna try setting up a dedicated server. You can set that up on your local machine, if you have some free ram that is.

**Comment by HermoidIronoak** [comment]
Thank you for the heads up! I'll look into that, though I'm not much for computer lingo... Could you recommend a guide somewheres that would walk me through the process of setting up a server on ones personal computer?

**Comment by way2muchnoise** [comment]
@HermoidIronfist http://minecraft.gamepedia.com/Tutorials/Setting_up_a_Minecraft_Forge_server or http://www.minecraftforge.net/forum/topic/18332-how-do-i-make-a-forge-server-multiplayer/

It comes down to downloading a forge server jar via their downloader available on http://files.minecraftforge.net/ (I recommend using the recommended version or what ever version your pack needs). After that it is basically the same as SP all you need to do is copy over your mods and config folders (to have the same on both side) or download a provided server version. Starting the server is done from the command line or making a `.bat` or `.sh` script. Usually with some params like `java -Xmx1G -Xms1G -jar forge.jar nogui` where you replace the `1G` with `2G` for example to allocate 2 gigs of ram instead of one. (You'll likely need 2gig at least, maybe even 3 not sure). The hosting pc can connect on the address `localhost` or `127.0.0.1`. Other pcs need to connect to the local IP of the server, most likely something in the form of `192.168.x.x`. That address can be found using the command prompt. (`ipconfig` for windows and `ifconfig` for linux or mac devices).

I think that describes most of it. Good luck!
