### ISSUE TITLE
HQM Failed to load questing state (Quests on server not working) (1.10.2)

### ISSUE THREAD

**Issue by Grammernatzi** [lorddusk/HQM#239]
Whenever I try to run HQM on a server, quests do not show up if I copy over the quest files to the server (along with the world). If I make new quests on the server, they show up, but I cannot complete them; detection does not work at all. Both times I get the error: [17:55:36] [Server thread/INFO] [HQM/HardcoreQuesting]: Failed to load questing state. It doesn't say anything more or less about the issue. I am not sure if it is a mod conflict or not. This is using someone else's modpack, not my own.

I am using the currently latest version of HQM for 1.10.2, which is New Heights 5.0.0 Beta 4.

Here is the full log:
[fml-server-latest.zip](https://github.com/lorddusk/HQM/files/507472/fml-server-latest.zip)

I should also mention this is with the default config files, at least on the server (not the client). I did not modify anything on the server for HQM aside from make a single quest.

**Comment by DaNeo61** [comment]
same here #249

**Comment by Saereth** [comment]
any update on this, is this mod still being maintained at all? @lorddusk @McJty ?

**Comment by royalcw** [comment]
- edit:  fixed by doing this:
"I had this problem also but figured it out. I removed the entire HQM subfolder from the config folder on the server. Next I booted up the server so that it could rebuild it's config for HQM. The config is actually slightly different when a server builds it and it also creates an additional folder called exports that isn't made in single player. Next I dragged all my quests from my client folder to the server Export folder and typed /hqm load all from in game as an OP. This loaded all the quests and now each player can see the quests. Hope this helped."

Same issue here.  Made a great 263 quest series and none of them show up when I upload them to the server.  They always show up just fine in single player.
