### ISSUE TITLE
[Request] Import Quest Option from BQM

### ISSUE THREAD

**Issue by Boolyman** [lorddusk/HQM#305]
Seeing as the other questing mod BQM has been dropped by many devs due to numerous unresolved issues, is there any way you can add the option to Import quests from that mod to your platform?  Some devs are stuck half way through their pack with hundreds of quests they would need to re-write if they wanted to switch to your mod

**Comment by way2muchnoise** [comment]
I should talk to @funwayguy about this, cause we would need some adaptors for it. Might be better as some addon or stand alone piece of code to convert his json to ours. Or at least as far as possible.

**Comment by Boolyman** [comment]
Looking forward to it, if possible.

**Comment by Funwayguy** [comment]
Currently busy with Uni, hence the recent lack of bug fixing from my side, but I'll look into what we can do for moving quests across. A big problem besides differences in JSON formatting is that HQM has a technical limit to the amount of quests it can support before things like network packets breakdown (unless that has since been fixed).

**Comment by way2muchnoise** [comment]
@Funwayguy the hard limit should be a lot higher then before now and if we ever hit it I'll look into fixing it.

**Comment by canitzp** [comment]
@Funwayguy any updates?

**Comment by noobanidus** [comment]
Does anyone know which adapters were missing?

**Comment by noobanidus** [comment]
After discussion with @Funwayguy this isn't really feasible at the minute. Perhaps after the rewrite.
