### ISSUE TITLE
Can't delete reputation bars/ reputation bars appear in the wrong quest page

### ISSUE THREAD

**Issue by binary-dragon** [lorddusk/HQM#333]
In edit mode, tried to add a bunch of rep bars to one quest page nothing happened. found them on a different quest group. (loads of them) they do not delete it seems, even though the save dialogue says that they are being deleted. they just stay there.

running lasted Alpha Available on Curse.

**Comment by binary-dragon** [comment]
<img width="1680" alt="screen shot 2017-05-27 at 4 16 56 pm" src="https://cloud.githubusercontent.com/assets/29007176/26524863/3d909d7a-42f8-11e7-963f-04f17e3ea508.png">
here a photo I placed them at the top, none of them will delete.

**Comment by tethlah** [comment]
I'm having this issue as well.  But since you posted this a month ago and he hasn't bothered to acknowledge you, I'm assuming it's telling us to fuck off on this one.  The best thing to do is not use that feature, you have to go into the horrifically structured jsons and remove the bars at the end, it'll look like this ""reputationBar":[]}"  Just empty it out and not use any reputation bars.

**Comment by TheQKnight** [comment]
Having this issue as well.

**Comment by canitzp** [comment]
Rewards are getting removed in the upcoming versions, since its sense and use arent worth keeping it
