### ISSUE TITLE
Crash from opening reward bag

### ISSUE THREAD

**Issue by Mindlessmrawesome** [lorddusk/HQM#493]
[crash-2019-06-02_14.45.24-client.txt](https://github.com/lorddusk/HQM/files/3245275/crash-2019-06-02_14.45.24-client.txt)

I was just testing out my rewards to see how they were going and then BOOM crashed on like the 10th bag

**Comment by noobanidus** [comment]
[HQM-1.12-5.4.0-hotfix2.jar.zip](https://github.com/lorddusk/HQM/files/3245425/HQM-1.12-5.4.0-hotfix2.jar.zip)

Can you try this build and see if you can get it to crash at all? It looks like the font renderer was null for whatever reason, but I'm not sure where in the code it gets set or where it could possibly have been unset...

This hotfix checks the font renderer, tries to reset it, and if it fails, doesn't render the screen instead of crashing.

**Comment by Funwayguy** [comment]
Odd, that variable should never be NULL under normal circumstances. Minecraft is in charge of setting it, not HQM, so I'm wondering what may have tampered with it. May want to experiment with which mods modify GUIs to narrow down a possible cause. The hotfix might as well be a bandaid solution to what appears to be a bigger issue (again, not likely HQM's fault).

Note: The Blur mod might be a good place to start although the source doesn't appear to touch the initialisation code. Could ask Tterrag about it if necessary.

**Comment by noobanidus** [comment]
I was in quite a daze when I woke up this morning and saw it, I'll admit. I couldn't possibly understand why the variable would be null... just that it was trying to draw something with a screen that wasn't properly set up as a screen?

Although I think I vaguely remember that fontRenderer as a member field is specific to HQM rather than to Minecraft.fontRenderer... unless I'm mistaken and I was actually looking at the original code for the Gui when I did ^B.

If you could try it without any mods that modify UI and see if it also crashes (not using the current hotfix), that would be good.

**Comment by Funwayguy** [comment]
The variable `fontRenderer` is specific to `GuiScreen.class` and set via `setWorldAndResolution()` when the GUI is opened via `Minecraft.displayGuiScreen()`. This is why I believe it's caused by another mod tampering with something it shouldn't (or at least in an unstable manner).

**Comment by Mindlessmrawesome** [comment]
that hotfix seemed to work, I went through about 500 quests and didn't crash.

**Comment by noobanidus** [comment]
Okay, based on Funway's information, I'm not going to release this hotfix as there's no reason why the fontRenderer should be null (I thought for some reason we were copying it at some point but obviously not). I would suggest removing the hotfix and removing a few of your UI mods and seeing if it still happens -- a sort of binary search but just with UI mods.
