### ISSUE TITLE
[1.16.5 fabric] BUG: tame task can‘t be finished 

### ISSUE THREAD

**Issue by CCCClear** [lorddusk/HQM#538]
I tested in the game only with the hqm mod. Its 1.16.5 fabric. And its the latest mod.

**Comment by kirderf1** [comment]
Tested this and can conclude that this is a **fabric-specific** issue.
The block state provided through the block break hook is the state after breaking (air), instead of the previous state (the block being broken). The hook is provided by cloth, so it should probably be fixed there unless a replacement is written in this mod.
The taming hook currently only has a mixin trigger for horse-like taming. That hook is simply incomplete and does not cover any other forms of taming. It'll need to be completed, or replaced by a complete hook from a dependency if such a hook exists.

I do not currently feel knowledgeable enough on modding practices in fabric (such as mixins) to attempt a solution, but perhaps someone else does.

**Comment by kirderf1** [comment]
To summarise the moths-old mentions:
- Both issues are fixed for the mc 1.17.1+ versions of HQM
- The block breaking issue is fixed for the mc 1.16.5 version of HQM
I'll edit the title to reflect this.
