### ISSUE TITLE
[1.16.5] A small issue I noticed with some text boxes.

### ISSUE THREAD

**Issue by vizthex123** [lorddusk/HQM#539]
I noticed that text written on the right side of a quest doesn't render apostrophes properly, whereas on the left side it works fine.

Pics attached.
Left side:
![image](https://user-images.githubusercontent.com/31721920/107718782-4c8dee00-6c9c-11eb-9486-bacd3ec25585.png)

Right side:
![image](https://user-images.githubusercontent.com/31721920/107718813-5e6f9100-6c9c-11eb-9c55-08c6251a77f9.png)

Text input on the right side: 
![image](https://user-images.githubusercontent.com/31721920/107718818-64657200-6c9c-11eb-8cc1-dc5be6c5d279.png)

**Comment by kirderf1** [comment]
Not sure what "Right side" editable text you're referring to. Can anyone elaborate?

**Comment by canitzp** [comment]
Probability the right and left side of the quest book itself

**Comment by kirderf1** [comment]
Not so sure. It has text on the right side (which seems to work while), while the left side is an image.
![quest book](https://user-images.githubusercontent.com/5451660/130751756-4a39f796-1173-4e58-8a1d-ebd254c413ce.png)

**Comment by vizthex123** [comment]
Yes I'm referring the the sides of the book. In my example they're from quests I made. You're able to test it by just typing apostrophes on each side in a quest description or something.

**Comment by kirderf1** [comment]
Ah, sorry about that. What I meant to ask about was the right side of _which menu_. Was also misled by a recent issue to not realize you could normally change the quest task descriptions.
Now with fewer misunderstandings, I was able to reproduce it.
It's a bit more unusual than just apostrophes not showing up there. For that text box, apostrophes only render when there are an odd number of them, or if there are two in a row.

**Comment by kirderf1** [comment]
Looks like this is caused by an issue in forge (MinecraftForge/MinecraftForge#7396). A workaround that can be implemented into HQM (PR coming up soon) would be to translate the task description using `I18n` instead of `TranslatableComponent`.
With the nature of this issue, similar problems are likely for translatable text in other parts of the mod. I'll do a search to see if I can spot any.

**Comment by kirderf1** [comment]
After looking around and realizing that a I18n-workaround is not appropriate for all such potential issues, I no longer find it worthwhile to fix this for HQM's own translatable text.
Also, as I've come to realize that what should be raw text shouldn't go through the translation procedure to begin with (see formatting characters such as %), I'll get rid of the translation of the task description entirely for now.

Due to this, for when we try and add back support for translatable quest text properly (and not just for task descriptions), we should keep a clear distinction between raw text and translation keys.
