### ISSUE TITLE
Request - Wiki tutorial?

### ISSUE THREAD

**Issue by DPxKnightxZero** [lorddusk/HQM#61]
I am confused as to how to use the quest creation system can you please write a tutorial? Its usage is foreign to newcomers.

**Comment by suprememiners** [comment]
I was thinking about seeing if I could get the wiki started, I must say though there are a few videos out there on youtube that explain either how to use it or the features on the mod and from there is not so hard to use.

Im not apose to the wiki, its just I dont have time to personally or solely do it and I doubt the mod devs do as they are devoted to the code rather than just the documentation.
