### ISSUE TITLE
Multiplayer Quests Reset Issue

### ISSUE THREAD

**Issue by CCCClear** [lorddusk/HQM#624]
In the latest version of 1.16.5 fabric, when a player dies in multiplayer (including the main server), everyone's quest progress will reset.
I don't know if this is a config setup error, hope you can help.

**Comment by kirderf1** [comment]
Gonna need to do some playtesting when I have the time for it. Until then, what settings are you using? Is HQM's hardcore mode with lives enabled? Did the players share a team or not? Anything else that you think might be relevant?

**Comment by CCCClear** [comment]
The HQM's hardcore mode with lives was not enabled. The players were all in one team. 
"MULTI_REWARD" and "ENABLE_TEAMS" are enabled. I don't think there are any death punishment options in the config. 
Default settings are mostly used in the game and settings

**Comment by kirderf1** [comment]
Alright, that should be enough for now. I'll ask for more details later if I am unable to recreate the issue myself.

**Comment by kirderf1** [comment]
@CCCClear
Was unable to recreate the issue. How consistent is it on your end? Is there any logged errors that might be related? If it is consistent enough, can you produce the minimal steps to recreate the issue?

**Comment by CCCClear** [comment]
Sorry for not replying to you for so long. I have been busy with my studies recently. 
I will find time to test one by one to find out the cause of the problem in my modpack.

**Comment by MSandro** [comment]
any news? i have the same issue in my modpack.

**Comment by 0gp** [comment]
very annoying bug, hope it can be fixed very soon for 1.17.1. Please.

**Comment by kirderf1** [comment]
Tried to reproduce this issue again in 1.17.1, but quests once again did not get reset. Without any solid lead, or an ability to reproduce the issue myself, I will not be able to do much with this issue.
@MSandro @0gp Since you are also experiencing this issue, can you give any more details on which circumstances that this issue happens under? Or can you answer any of the questions I asked CCCClear?

**Comment by MSandro** [comment]
found the problem, I am running an Akliz Server and the Restart Schedules are not shutting down the Server correctly, it seems that the server will be killed. HQM just saves the Quest Status in the World Folder with an proper shutdown task.

**Suggestion:**
Would it be possible to save HQM Player Data while the server does an "save-all"? Would be nice, because if the server crashes, the HQM data will not be saved!

**Comment by canitzp** [comment]
That is definitely possible and I am wondering why this is not done already.

**Comment by kirderf1** [comment]
Yep, that looks to be all info I need.
Looks like an event hook for world unload was unintentionally used instead of world save. Didn't see a world save event in architectury api, but there is one in fabric api, so it should be a simple fix. Gonna take care of it tomorrow, so a fix should be out in a day or so.

**Comment by 0gp** [comment]
Thank you very much, could you backport this fix to 1.17.1 please?

**Comment by kirderf1** [comment]
Oops, I got my class names mixed up yesterday night. Fabric api was what we were using, and architectury api had a world save event. Either way, I'll be gettning out a fix for 1.18, 1.17 and 1.16 during the day as I get time.

**Comment by kirderf1** [comment]
Versions have now been uploaded.
