### ISSUE TITLE
[Feature Request 1.18.1] Moving up and down

### ISSUE THREAD

**Issue by itsdinkd** [lorddusk/HQM#637]
Right now there is no way to move sets / tasks up or down. So if you decided to change the order of something like moving a task all the way from spot #3 to spot #1, you are forced to delete the first two tasks, as well as the sets. This can be troublesome if you are deep in sets, and have content already stored.

**Comment by kirderf1** [comment]
Moving quest sets has previously been mentioned in #489 and #524, but moving quest tasks hasn't been mentioned before.

**Comment by itsdinkd** [comment]
Question; what are usual timelines for accepted feature Requests? The first one I accidently duplicated was requested 2 years ago, and this one 1 year ago.

**Comment by kirderf1** [comment]
HQM does not have any dedicated developers, so there is little to go by. If it's motivated to be particularly important and/or easy to implement, that may help give it more attention.

For now, if you understand enough about how the json data is structured, you should be able able to move things around directly in the data files fairly easy.
Quest sets should be very easy to move around that way, since the order should just be the order that their names appear in `sets.json`. Quest tasks are a bit trickier to move that way, since you need to move the whole quest task, and not just a name reference.
