### ISSUE TITLE
Shift-clicking does not count towards crafting tasks in quests

### ISSUE THREAD

**Issue by zalwicker2** [lorddusk/HQM#641]
Using HQM-1.16.5-5.5.15. When doing crafting quests, shift-clicking the crafted item into your inventory causes the quest to not be completed.

**Comment by kirderf1** [comment]
Does this happen with fabric or forge?

**Comment by zalwicker2** [comment]
On Forge, specifically in the [Permafrost Modpack](https://www.curseforge.com/minecraft/modpacks/permafrost-eots)

**Comment by kirderf1** [comment]
Tested this in forge 1.16.5 with just HQM by crafting oak planks. It worked fine both when clicking regularly and when shift-clicking. Perhaps some other mod is causing interference?
Could you test around a bit and see if this is caused by the presence of a different mod, or if this has to do with the type of item being crafted? It is also possible that it's caused by a specific version of forge (the dev environment happen to be using forge 36.2.2 currently)

**Comment by canitzp** [comment]
Closed because of inactivity.
