### ISSUE TITLE
Spawn with book not working / detection task creation crash

### ISSUE THREAD

**Issue by TheeMrCheeky** [lorddusk/HQM#657]
Fabric - 0.14.4
MC Version - 1.18.2
HQM-1.18.2-5.10.1-fabric.jar 

Ran it with no mods minus it and still don't spawn in world with book option enabled

SCRATCH THAT it only happens with edit mode enabled Idk if that is to be expected or not! My apologies 

Also getting a crash when making detection task

[crash-2022-05-04_13.00.34-client.txt](https://github.com/lorddusk/HQM/files/8623354/crash-2022-05-04_13.00.34-client.txt)

**Comment by kirderf1** [comment]
Found what looks to be the same crash in AHilyard/LegendaryTooltips#24.
The crash seems to happen in a mixin from another mod, which I highly suspect is from levelz at https://github.com/Globox1997/LevelZ/blob/fb01405bcfcf21721ea95dbe93140ac72257df71/src/main/java/net/levelz/mixin/item/ItemStackClientMixin.java#L68
I don't think that this crash has anything to do with HQM or LegendaryTooltips, and believe that the issue is specifically at levelz's end.

**Comment by TheeMrCheeky** [comment]
Ya! After a lot of trial an error I narrowed it down to levelz as well. Apologies
