### ISSUE TITLE
Quest Delivery/Tracking Systems Do Not Have Loot Tables

### ISSUE THREAD

**Issue by Darkosto** [lorddusk/HQM#661]
Hello!

Both the Quest Delivery System & Quest Tracking System do not have loot tables so they do not drop the blocks when broken. Also, the Quest Delivery System does not have a hardness so it will break in a single hit. The Quest Tracking System does have a hardness.

MC: 1.18.2 
Forge: 40.1.73
HQM: 5.11.0

**Comment by kirderf1** [comment]
> Both the Quest Delivery System & Quest Tracking System do not have loot tables so they do not drop the blocks when broken.

Can confirm. Seems like the quest tracking system is a map-making tool that shouldn't be set up and used by a regular player. As such, I suggest that the loot table for quest tracking system is made to not drop anything.

Also, I'm seeing that the quest delivery system is configured to require the correct tool (being an axe) to drop if it did have a loot table. That doesn't seem right as I see tool use for that block comparable to tool use for a vanilla chest, barrel or crafting table.

> Also, the Quest Delivery System does not have a hardness so it will break in a single hit.

I am not experiencing this issue on my end, and both blocks have hardness/strength values assigned in code. Might be interference from outside the mod, but that is difficult to say without more information.

So my suggested changes to resolve this issue is to:
- Add an empty loot table to the quest tracking system block
- Add a regular, self-dropping loot table to the quest delivery system block
- Change the quest delivery system block to not require any tool to drop when broken

Does this seem fine?

Also, @canitzp should I make a PR for these changes, or am I fine to push them directly onto the 1.18 branch?

**Comment by canitzp** [comment]
Do it directly

**Comment by kirderf1** [comment]
5.11.1 has now been released with the listed changes

**Comment by kirderf1** [comment]
@Darkosto any news or additional info on the block hardness issue? Is it still an issue with HQM 5.11.1? And if so, do you have any more information on reproducing the issue?

**Comment by Darkosto** [comment]
@kirderf1 Thanks for being patient, I just confirmed that the Quest Delivery System does have a proper hardness and drops itself when broken. I'm a bit confused though since the hardness didn't seem to be a problem when testing the old version of HQM in a pack by itself (this must have been another mod?). 

The Quest Tracking System I was not aware shouldn't be accessible by survival players and is functioning as intended. 

Looks like everything in the update is in working order. Thanks for the follow up and addition of the loot table!
