### ISSUE TITLE
Request: API for creating custom Quest tasks via addons

### ISSUE THREAD

**Issue by JTBWatchDog** [lorddusk/HQM#670]
~~Specifically for Pixelmon and making new tasks.
I have tried simply reading through the code.
I am in immense pain.
Any and all help is greatly appreciated.~~

**Comment by canitzp** [comment]
The code is old, but I have read much worse.
Yeah it is not easy, since a lot of stuff needs to be rewritten, but no one has the time to tackle everything. Currently Kirderf knows most about it, you may be able to ask him here or on our discord

**Comment by kirderf1** [comment]
There is not much in the way of api for potential addons to use at this time, but it is something that I think we should make.
More specifically, there are currently no proper ways for an addon to add new types of quest tasks.
While I have previously done a little bit of work towards this (#623), there are still a few things that need to be updated for addons to add new quest tasks:
- The list of task buttons in `QuestGraphic` need to be updated so that it can handle more types of quest tasks than can fit within the gui at the same time, such as through a scroll bar.
- The private map that keeps track of all possible types of quest tasks need to be replaced with a registry that other mods can use and register new types to.
We should also describe the api somewhere afterwards, though I am not sure where a suitable place would be.

I'd suggest rebranding this issue to be about adding api for making new types of quest tasks.
