### ISSUE TITLE
[Question] The kill count feature

### ISSUE THREAD

**Issue by KarishaDel** [lorddusk/HQM#674]
Ello! I have two questions.
1. Is there a way to count overall kills? Like kill 1000 enemies? Mix between all enemies.
2. Is there a way to say 'kill zombies 40' and this includes baby zombies and other types from other mods?
Thanks!

**Comment by kirderf1** [comment]
Not at the moment, no. There is a task for killing mobs, but it only checks against a single entity type for each requirement. Zombies and baby zombies share an entity type, but otherwise you'll be unable to do this until support for it is added in HQM.
I think the way to support it in HQM is to change the kill task to let it use either an entity type or an entity type tag, perhaps through a holder set of entity types (I think that's how holder sets work).

**Comment by KarishaDel** [comment]
Another question. Is there a way to combine two books so we can split the
work of making the quest?

**Comment by kirderf1** [comment]
There is no feature in the mod itself for that, but it should only take a basic understanding of the json data to combine the data files together. Some files would just be moved over, but files that share a name would need their content combined, which should be pretty straightforward if you open those files in a text editor.
